KNN alogrthium

K-Nearest Neighbors (KNN)

KNN computes the distance from the new sample to every training sample, selects the K closest ones, counts their class labels, and returns the class with the most votes as the single output.


d=underroot(x2​−x1​)^2+(y2​−y1​)^2

much much less distance better classification

k is the no of friends
high no of k better classification

low k less classification
​

to calculate k algo method is there

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder , StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [ ]:
data = pd.read_csv('dataset/credit_risk_dataset.csv')

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32581 non-null  int64
 1   person_income               32581 non-null  int64
 2   person_home_ownership       32581 non-null  str
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  str
 5   loan_grade                  32581 non-null  str
 6   loan_amnt                   32581 non-null  int64
 7   loan_int_rate               29465 non-null  float64
 8   loan_status                 32581 non-null  int64
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  str
 11  cb_person_cred_hist_length  32581 non-null  int64
dtypes: float64(3), int64(5), str(4)
memory usage: 3.0 MB

In [4]:
data.isnull().sum()

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              895
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3116
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [5]:
data['person_emp_length'] = data['person_emp_length'].fillna(data['person_emp_length'].median())

In [6]:
data['loan_int_rate'] = data['loan_int_rate'].fillna(data['loan_int_rate'].median())

In [7]:
data.isnull().sum()

person_age                    0
person_income                 0
person_home_ownership         0
person_emp_length             0
loan_intent                   0
loan_grade                    0
loan_amnt                     0
loan_int_rate                 0
loan_status                   0
loan_percent_income           0
cb_person_default_on_file     0
cb_person_cred_hist_length    0
dtype: int64

In [8]:
data.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [9]:
home_encoder = LabelEncoder()
intent_encoder = LabelEncoder()
grade_encoder = LabelEncoder()
default_encoder = LabelEncoder()

In [10]:
data["person_home_ownership"] = home_encoder.fit_transform(data["person_home_ownership"])

data["loan_intent"] = intent_encoder.fit_transform(data["loan_intent"])

data["loan_grade"] = grade_encoder.fit_transform(data["loan_grade"])

data["cb_person_default_on_file"] = default_encoder.fit_transform(data["cb_person_default_on_file"])

In [ ]:
# encoder = LabelEncoder()

In [ ]:
# data['person_home_ownership'] = encoder.fit_transform(data['person_home_ownership'])
# data['loan_intent'] = encoder.fit_transform(data['loan_intent'])
# data['loan_grade'] = encoder.fit_transform(data['loan_grade'])
# data['cb_person_default_on_file'] = encoder.fit_transform(data['cb_person_default_on_file'])

In [11]:
data.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,3,123.0,4,3,35000,16.02,1,0.59,1,3
1,21,9600,2,5.0,1,1,1000,11.14,0,0.10,0,2
2,25,9600,0,1.0,3,2,5500,12.87,1,0.57,0,3
3,23,65500,3,4.0,3,2,35000,15.23,1,0.53,0,2
4,24,54400,3,8.0,3,2,35000,14.27,1,0.55,1,4

In [12]:
x = data.drop('loan_status',axis=1)
y = data['loan_status']

In [13]:
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [14]:
scalar = StandardScaler()

In [15]:
# X_train = scalar.fit_transform(X_train)
# X_test = scalar.fit_transform(X_test)

X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [16]:
model = KNeighborsClassifier(n_neighbors=3)

In [17]:
model.fit(X_train,Y_train)

KNeighborsClassifier(n_neighbors=3)

In [18]:
model.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0], shape=(6517,))

In [18]:
print("accuracy")
print(accuracy_score(Y_test,model.predict(X_test)))

accuracy
0.8701856682522633

In [19]:
from sklearn.metrics import  classification_report

In [20]:
print("classification")
print(classification_report(Y_test,model.predict(X_test)))

classification
              precision    recall  f1-score   support

           0       0.89      0.95      0.92      5072
           1       0.76      0.60      0.67      1445

    accuracy                           0.87      6517
   macro avg       0.83      0.77      0.80      6517
weighted avg       0.86      0.87      0.86      6517

In [ ]:
# import pickle

# pickle.dump(model, open('model_credit.pkl', 'wb'))

In [22]:
import pickle

pickle.dump(model, open("model_credit.pkl", "wb"))

pickle.dump(scalar, open("scaler.pkl", "wb"))

pickle.dump(home_encoder, open("home_encoder.pkl", "wb"))

pickle.dump(intent_encoder, open("intent_encoder.pkl", "wb"))

pickle.dump(grade_encoder, open("grade_encoder.pkl", "wb"))

pickle.dump(default_encoder, open("default_encoder.pkl", "wb"))

In [24]:
print(x.columns)

Index(['person_age', 'person_income', 'person_home_ownership',
       'person_emp_length', 'loan_intent', 'loan_grade', 'loan_amnt',
       'loan_int_rate', 'loan_percent_income', 'cb_person_default_on_file',
       'cb_person_cred_hist_length'],
      dtype='str')

In [25]:
print(home_encoder.classes_)
print(intent_encoder.classes_)
print(grade_encoder.classes_)
print(default_encoder.classes_)

['MORTGAGE' 'OTHER' 'OWN' 'RENT']
['DEBTCONSOLIDATION' 'EDUCATION' 'HOMEIMPROVEMENT' 'MEDICAL' 'PERSONAL'
 'VENTURE']
['A' 'B' 'C' 'D' 'E' 'F' 'G']
['N' 'Y']